In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data_path = "./Data/hour.csv"
rides = pd.read_csv(data_path)

In [3]:
rides.head()

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,3,13,16
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,8,32,40
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,5,27,32
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0,3,10,13
4,5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0,0,1,1

In [4]:
rides[:24*10].plot(x="dteday",y="cnt")

In [5]:
dummy_fields=['season','weathersit','mnth','hr','weekday']
for each in dummy_fields:
    dummies = pd.get_dummies(rides[each],prefix=each,drop_first=False)
    rides = pd.concat([rides,dummies],axis=1)

col_to_drop = ['instant','dteday','season','weathersit','weekday','atemp','mnth','workingday','hr']
data = rides.drop(col_to_drop,axis=1)
data.head()

,yr,holiday,temp,hum,windspeed,casual,registered,cnt,season_1,season_2,...,hr_21,hr_22,hr_23,weekday_0,weekday_1,weekday_2,weekday_3,weekday_4,weekday_5,weekday_6
0,0,0,0.24,0.81,0.0,3,13,16,1,0,...,0,0,0,0,0,0,0,0,0,1
1,0,0,0.22,0.80,0.0,8,32,40,1,0,...,0,0,0,0,0,0,0,0,0,1
2,0,0,0.22,0.80,0.0,5,27,32,1,0,...,0,0,0,0,0,0,0,0,0,1
3,0,0,0.24,0.75,0.0,3,10,13,1,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0.24,0.75,0.0,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,1

In [6]:
data.head(10)

,yr,holiday,temp,hum,windspeed,casual,registered,cnt,season_1,season_2,...,hr_21,hr_22,hr_23,weekday_0,weekday_1,weekday_2,weekday_3,weekday_4,weekday_5,weekday_6
0,0,0,0.24,0.81,0.0000,3,13,16,1,0,...,0,0,0,0,0,0,0,0,0,1
1,0,0,0.22,0.80,0.0000,8,32,40,1,0,...,0,0,0,0,0,0,0,0,0,1
2,0,0,0.22,0.80,0.0000,5,27,32,1,0,...,0,0,0,0,0,0,0,0,0,1
3,0,0,0.24,0.75,0.0000,3,10,13,1,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0.24,0.75,0.0000,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,1
5,0,0,0.24,0.75,0.0896,0,1,1,1,0,...,0,0,0,0,0,0,0,0,0,1
6,0,0,0.22,0.80,0.0000,2,0,2,1,0,...,0,0,0,0,0,0,0,0,0,1
7,0,0,0.20,0.86,0.0000,1,2,3,1,0,...,0,0,0,0,0,0,0,0,0,1
8,0,0,0.24,0.75,0.0000,1,7,8,1,0,...,0,0,0,0,0,0,0,0,0,1
9,0,0,0.32,0.76,0.0000,8,6,14,1,0,...,0,0,0,0,0,0,0,0,0,1

In [7]:
col_cont = ['temp','hum','windspeed','casual','registered','cnt']
data2=data
for each in col_cont:
    data2[each]=(data[each]-data[each].min())/(data[each].max()-data[each].min())

In [8]:
data2.head(10)

,yr,holiday,temp,hum,windspeed,casual,registered,cnt,season_1,season_2,...,hr_21,hr_22,hr_23,weekday_0,weekday_1,weekday_2,weekday_3,weekday_4,weekday_5,weekday_6
0,0,0,0.224490,0.81,0.000000,0.008174,0.014673,0.015369,1,0,...,0,0,0,0,0,0,0,0,0,1
1,0,0,0.204082,0.80,0.000000,0.021798,0.036117,0.039959,1,0,...,0,0,0,0,0,0,0,0,0,1
2,0,0,0.204082,0.80,0.000000,0.013624,0.030474,0.031762,1,0,...,0,0,0,0,0,0,0,0,0,1
3,0,0,0.224490,0.75,0.000000,0.008174,0.011287,0.012295,1,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0.224490,0.75,0.000000,0.000000,0.001129,0.000000,1,0,...,0,0,0,0,0,0,0,0,0,1
5,0,0,0.224490,0.75,0.105325,0.000000,0.001129,0.000000,1,0,...,0,0,0,0,0,0,0,0,0,1
6,0,0,0.204082,0.80,0.000000,0.005450,0.000000,0.001025,1,0,...,0,0,0,0,0,0,0,0,0,1
7,0,0,0.183673,0.86,0.000000,0.002725,0.002257,0.002049,1,0,...,0,0,0,0,0,0,0,0,0,1
8,0,0,0.224490,0.75,0.000000,0.002725,0.007901,0.007172,1,0,...,0,0,0,0,0,0,0,0,0,1
9,0,0,0.306122,0.76,0.000000,0.021798,0.006772,0.013320,1,0,...,0,0,0,0,0,0,0,0,0,1

In [9]:
quant_features = ['casual', 'registered', 'cnt', 'temp', 'hum', 'windspeed']
data3 = data
# Store scalings in a dictionary so we can convert back later
scaled_features = {}
for each in quant_features:
    mean, std = data[each].mean(), data[each].std()
    scaled_features[each] = [mean, std]
    data3.loc[:, each] = (data[each] - mean)/std

In [10]:
data3.head(10)

,yr,holiday,temp,hum,windspeed,casual,registered,cnt,season_1,season_2,...,hr_21,hr_22,hr_23,weekday_0,weekday_1,weekday_2,weekday_3,weekday_4,weekday_5,weekday_6
0,0,0,-1.334609,0.947345,-1.553844,-0.662736,-0.930162,-0.956312,1,0,...,0,0,0,0,0,0,0,0,0,1
1,0,0,-1.438475,0.895513,-1.553844,-0.561326,-0.804632,-0.823998,1,0,...,0,0,0,0,0,0,0,0,0,1
2,0,0,-1.438475,0.895513,-1.553844,-0.622172,-0.837666,-0.868103,1,0,...,0,0,0,0,0,0,0,0,0,1
3,0,0,-1.334609,0.636351,-1.553844,-0.662736,-0.949983,-0.972851,1,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,-1.334609,0.636351,-1.553844,-0.723582,-1.009445,-1.039008,1,0,...,0,0,0,0,0,0,0,0,0,1
5,0,0,-1.334609,0.636351,-0.821460,-0.723582,-1.009445,-1.039008,1,0,...,0,0,0,0,0,0,0,0,0,1
6,0,0,-1.438475,0.895513,-1.553844,-0.683018,-1.016052,-1.033495,1,0,...,0,0,0,0,0,0,0,0,0,1
7,0,0,-1.542341,1.206507,-1.553844,-0.703300,-1.002838,-1.027981,1,0,...,0,0,0,0,0,0,0,0,0,1
8,0,0,-1.334609,0.636351,-1.553844,-0.703300,-0.969804,-1.000416,1,0,...,0,0,0,0,0,0,0,0,0,1
9,0,0,-0.919146,0.688184,-1.553844,-0.561326,-0.976411,-0.967338,1,0,...,0,0,0,0,0,0,0,0,0,1

In [11]:
test_data = data3[-21*24:]

data4=data3[:-21*24]

target_fields=['cnt','casual','registered']
features,targets = data4.drop(target_fields,axis=1),data4[target_fields]

test_features, test_targets = test_data.drop(target_fields,axis=1),test_data[target_fields]

In [12]:
data4.shape

(16875, 59)

In [13]:
data3.shape

(17379, 59)

In [14]:
# Hold out the last 60 days or so of the remaining data as a validation set
train_features, train_targets = features[:-60*24], targets[:-60*24]

val_features, val_targets = features[-60*24:],targets[-60*24:]

In [16]:
iterations = 100
learning_rate = 0.1
hidden_nodes = 2
output_nodes = 1

In [17]:
def MSE(y, Y):
    return np.mean((y-Y)**2)

In [65]:
class NeuralNetwork(object):
    def __init__(self, input_nodes, hidden_nodes, output_nodes, learning_rate):
        # Set number of nodes in input, hidden and output layers.
        self.input_nodes = input_nodes
        self.hidden_nodes = hidden_nodes
        self.output_nodes = output_nodes

        # Initialize weights
        self.weights_input_to_hidden = np.random.normal(0.0, self.hidden_nodes**-0.5, 
                                       (self.hidden_nodes, self.input_nodes))

        self.weights_hidden_to_output = np.random.normal(0.0, self.output_nodes**-0.5, 
                                       (self.output_nodes, self.hidden_nodes))
        self.lr = learning_rate
        
        #### Set this to your implemented sigmoid function ####
        # Activation function is the sigmoid function
        self.activation_function = lambda x:1/(1 + np.exp(-x))
        self.sigmoid_derivate = lambda x:x*(1 - x)
    
    def train(self, inputs_list, targets_list):
        # Convert inputs list to 2d array
        inputs = np.array(inputs_list, ndmin=2).T
        targets = np.array(targets_list, ndmin=2).T
        #### Implement the forward pass here ####
        ### Forward pass ###
        # TODO: Hidden layer
        # signals into hidden layer
        hidden_inputs = np.dot(self.weights_input_to_hidden, inputs)
        # signals from hidden layer
        hidden_outputs = self.activation_function(hidden_inputs)
        
        # TODO: Output layer
        # signals into final output layer
        final_inputs = np.dot(self.weights_hidden_to_output, hidden_outputs)
        # signals from final output layer
        final_outputs = final_inputs
        
        #### Implement the backward pass here ####
        ### Backward pass ###
        
        # TODO: Output error
        # Output layer error is the difference between desired target and actual output.
        output_errors = targets - final_outputs
        
        # TODO: Backpropagated error
        # errors propagated to the hidden layer
        hidden_errors = np.dot(self.weights_hidden_to_output.T, output_errors)
        # hidden layer gradients
        hidden_grad = self.sigmoid_derivate(hidden_outputs)
        
        # TODO: Update the weights
        # update hidden-to-output weights with gradient descent step
        self.weights_hidden_to_output += self.lr * np.dot(output_errors, hidden_outputs.T)
        # update input-to-hidden weights with gradient descent step
        self.weights_input_to_hidden += self.lr * np.dot(hidden_grad*hidden_errors, inputs.T)
 
        
    def run(self, inputs_list):
        # Run a forward pass through the network
        inputs = np.array(inputs_list, ndmin=2).T
        
        #### Implement the forward pass here ####
        # TODO: Hidden layer
        # signals into hidden layer
        hidden_inputs = np.dot(self.weights_input_to_hidden, inputs)
        # signals from hidden layer
        hidden_outputs = self.activation_function(hidden_inputs)
        
        # TODO: Output layer
        # signals into final output layer
        final_inputs = np.dot(self.weights_hidden_to_output, hidden_outputs)
        # signals from final output layer 
        final_outputs = final_inputs
        
        return final_outputs

In [66]:
import sys

### Set the hyperparameters here ###
epochs = 5000
learning_rate = 0.08
hidden_nodes = 12
output_nodes = 1

N_i = train_features.shape[1]
network = NeuralNetwork(N_i, hidden_nodes, output_nodes, learning_rate)

losses = {'train':[], 'validation':[]}
for e in range(epochs):
    # Go through a random batch of 128 records from the training data set
    batch = np.random.choice(train_features.index, size=128)
    for record, target in zip(train_features.ix[batch].values, 
                              train_targets.ix[batch]['cnt']):
        network.train(record, target)
    
    # Printing out the training progress
    train_loss = MSE(network.run(train_features), train_targets['cnt'].values)
    val_loss = MSE(network.run(val_features), val_targets['cnt'].values)
    sys.stdout.write("\rProgress: " + str(100 * e/float(epochs))[:4] \
                     + "% ... Training loss: " + str(train_loss)[:5] \
                     + " ... Validation loss: " + str(val_loss)[:5])
    
    losses['train'].append(train_loss)
    losses['validation'].append(val_loss)

Progress: 99.9% ... Training loss: 0.050 ... Validation loss: 0.182

In [67]:
plt.plot(losses['train'], label='Training loss')
plt.plot(losses['validation'], label='Validation loss')
plt.legend()
_ = plt.ylim()

In [68]:
fig, ax = plt.subplots(figsize=(8,4))

mean, std = scaled_features['cnt']
predictions = network.run(test_features).T*std + mean
ax.plot(predictions[0], label='Prediction')
ax.plot((test_targets['cnt']*std + mean).values, label='Data')
ax.set_xlim(right=len(predictions))
ax.legend()

dates = pd.to_datetime(rides.ix[test_data.index]['dteday'])
dates = dates.apply(lambda d: d.strftime('%b %d'))
ax.set_xticks(np.arange(len(dates))[12::24])
_ = ax.set_xticklabels(dates[12::24], rotation=45)

/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:10: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

In [69]:
import sys

### Set the hyperparameters here ###
epochs = 10000
learning_rate = 0.08
hidden_nodes = 24
output_nodes = 1

N_i = train_features.shape[1]
network = NeuralNetwork(N_i, hidden_nodes, output_nodes, learning_rate)

losses = {'train':[], 'validation':[]}
for e in range(epochs):
    # Go through a random batch of 128 records from the training data set
    batch = np.random.choice(train_features.index, size=128)
    for record, target in zip(train_features.ix[batch].values, 
                              train_targets.ix[batch]['cnt']):
        network.train(record, target)
    
    # Printing out the training progress
    train_loss = MSE(network.run(train_features), train_targets['cnt'].values)
    val_loss = MSE(network.run(val_features), val_targets['cnt'].values)
    sys.stdout.write("\rProgress: " + str(100 * e/float(epochs))[:4] \
                     + "% ... Training loss: " + str(train_loss)[:5] \
                     + " ... Validation loss: " + str(val_loss)[:5])
    
    losses['train'].append(train_loss)
    losses['validation'].append(val_loss)

Progress: 99.9% ... Training loss: 0.044 ... Validation loss: 0.146